apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "hackdb.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "hackdb.fullname" . }}
    release: {{ .Release.Name }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-url: {{ tpl .Values.ingress.authURL . }}
    nginx.ingress.kubernetes.io/auth-response-headers: {{ .Values.ingress.authResponseHeaders }}
    nginx.ingress.kubernetes.io/limit-rps: "{{ .Values.ingress.limitRps }}"
    nginx.ingress.kubernetes.io/rewrite-target: {{ .Values.ingress.rewriteTarget }}
spec:
  rules:
  - host: env-1.test.infoblox.com
    http:
      paths:
      - path: {{ .Values.ingress.http.path }}
        backend:
          serviceName: {{ tpl .Values.notifications.hackdb.serviceName .}}
          servicePort: 8080
  tls:
  - hosts:
    - env-1.test.infoblox.com
    secretName: "csp-cert"
