apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.notifications.hackdb.serviceName }}
  namespace: {{ .Release.Namespace }}
  labels:
    name: {{ include "hackdb.name" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    promlabel: {{ tpl .Values.notifications.hackdb.matchServiceLabel . }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.notifications.hackdb.httpPort }}
    targetPort: http
    protocol: TCP
    name: http
  - port: {{ .Values.notifications.hackdb.grpcPort }}
    targetPort: grpc
    protocol: TCP
    name: grpc
  selector:
    name: {{ include "hackdb.name" . }}
    release: {{ .Release.Name }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.notifications.hackdb.serviceName }}-ui
  namespace: {{ .Release.Namespace }}
  labels:
    name: {{ include "hackdb.name" . }}-ui
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    promlabel: {{ tpl .Values.notifications.hackdb.matchServiceLabel . }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 4200
      protocol: TCP
      name: http
  selector:
    name: {{ include "hackdb.name" . }}-ui
    release: {{ .Release.Name }}