// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/brocwoodworthIBLX/hack-db/pkg/pb/service.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	query "github.com/infobloxopen/atlas-app-toolkit/query"
	_ "github.com/infobloxopen/protoc-gen-gorm/options"
	types "github.com/infobloxopen/protoc-gen-gorm/types"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Submission struct {
	Id                   *types.UUIDValue `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string           `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Submission           string           `protobuf:"bytes,3,opt,name=submission,proto3" json:"submission,omitempty"`
	SubmittedBy          string           `protobuf:"bytes,4,opt,name=submitted_by,json=submittedBy,proto3" json:"submitted_by,omitempty"`
	Tags                 string           `protobuf:"bytes,5,opt,name=tags,proto3" json:"tags,omitempty"`
	Votes                int32            `protobuf:"varint,6,opt,name=votes,proto3" json:"votes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Submission) Reset()         { *m = Submission{} }
func (m *Submission) String() string { return proto.CompactTextString(m) }
func (*Submission) ProtoMessage()    {}
func (*Submission) Descriptor() ([]byte, []int) {
	return fileDescriptor_f73f7111cf4d69d9, []int{0}
}

func (m *Submission) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Submission.Unmarshal(m, b)
}
func (m *Submission) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Submission.Marshal(b, m, deterministic)
}
func (m *Submission) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Submission.Merge(m, src)
}
func (m *Submission) XXX_Size() int {
	return xxx_messageInfo_Submission.Size(m)
}
func (m *Submission) XXX_DiscardUnknown() {
	xxx_messageInfo_Submission.DiscardUnknown(m)
}

var xxx_messageInfo_Submission proto.InternalMessageInfo

func (m *Submission) GetId() *types.UUIDValue {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Submission) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Submission) GetSubmission() string {
	if m != nil {
		return m.Submission
	}
	return ""
}

func (m *Submission) GetSubmittedBy() string {
	if m != nil {
		return m.SubmittedBy
	}
	return ""
}

func (m *Submission) GetTags() string {
	if m != nil {
		return m.Tags
	}
	return ""
}

func (m *Submission) GetVotes() int32 {
	if m != nil {
		return m.Votes
	}
	return 0
}

type CreateSubmissionRequest struct {
	Payload              *Submission `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreateSubmissionRequest) Reset()         { *m = CreateSubmissionRequest{} }
func (m *CreateSubmissionRequest) String() string { return proto.CompactTextString(m) }
func (*CreateSubmissionRequest) ProtoMessage()    {}
func (*CreateSubmissionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f73f7111cf4d69d9, []int{1}
}

func (m *CreateSubmissionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSubmissionRequest.Unmarshal(m, b)
}
func (m *CreateSubmissionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSubmissionRequest.Marshal(b, m, deterministic)
}
func (m *CreateSubmissionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSubmissionRequest.Merge(m, src)
}
func (m *CreateSubmissionRequest) XXX_Size() int {
	return xxx_messageInfo_CreateSubmissionRequest.Size(m)
}
func (m *CreateSubmissionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSubmissionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSubmissionRequest proto.InternalMessageInfo

func (m *CreateSubmissionRequest) GetPayload() *Submission {
	if m != nil {
		return m.Payload
	}
	return nil
}

type CreateSubmissionResponse struct {
	Result               *Submission `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreateSubmissionResponse) Reset()         { *m = CreateSubmissionResponse{} }
func (m *CreateSubmissionResponse) String() string { return proto.CompactTextString(m) }
func (*CreateSubmissionResponse) ProtoMessage()    {}
func (*CreateSubmissionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f73f7111cf4d69d9, []int{2}
}

func (m *CreateSubmissionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSubmissionResponse.Unmarshal(m, b)
}
func (m *CreateSubmissionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSubmissionResponse.Marshal(b, m, deterministic)
}
func (m *CreateSubmissionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSubmissionResponse.Merge(m, src)
}
func (m *CreateSubmissionResponse) XXX_Size() int {
	return xxx_messageInfo_CreateSubmissionResponse.Size(m)
}
func (m *CreateSubmissionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSubmissionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSubmissionResponse proto.InternalMessageInfo

func (m *CreateSubmissionResponse) GetResult() *Submission {
	if m != nil {
		return m.Result
	}
	return nil
}

type ListSubmissionRequest struct {
	Filter               *query.Filtering      `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	OrderBy              *query.Sorting        `protobuf:"bytes,2,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	Fields               *query.FieldSelection `protobuf:"bytes,3,opt,name=fields,proto3" json:"fields,omitempty"`
	Paging               *query.Pagination     `protobuf:"bytes,4,opt,name=paging,proto3" json:"paging,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ListSubmissionRequest) Reset()         { *m = ListSubmissionRequest{} }
func (m *ListSubmissionRequest) String() string { return proto.CompactTextString(m) }
func (*ListSubmissionRequest) ProtoMessage()    {}
func (*ListSubmissionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f73f7111cf4d69d9, []int{3}
}

func (m *ListSubmissionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSubmissionRequest.Unmarshal(m, b)
}
func (m *ListSubmissionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSubmissionRequest.Marshal(b, m, deterministic)
}
func (m *ListSubmissionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSubmissionRequest.Merge(m, src)
}
func (m *ListSubmissionRequest) XXX_Size() int {
	return xxx_messageInfo_ListSubmissionRequest.Size(m)
}
func (m *ListSubmissionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSubmissionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListSubmissionRequest proto.InternalMessageInfo

func (m *ListSubmissionRequest) GetFilter() *query.Filtering {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *ListSubmissionRequest) GetOrderBy() *query.Sorting {
	if m != nil {
		return m.OrderBy
	}
	return nil
}

func (m *ListSubmissionRequest) GetFields() *query.FieldSelection {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *ListSubmissionRequest) GetPaging() *query.Pagination {
	if m != nil {
		return m.Paging
	}
	return nil
}

type ListSubmissionResponse struct {
	Results              []*Submission `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ListSubmissionResponse) Reset()         { *m = ListSubmissionResponse{} }
func (m *ListSubmissionResponse) String() string { return proto.CompactTextString(m) }
func (*ListSubmissionResponse) ProtoMessage()    {}
func (*ListSubmissionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f73f7111cf4d69d9, []int{4}
}

func (m *ListSubmissionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSubmissionResponse.Unmarshal(m, b)
}
func (m *ListSubmissionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSubmissionResponse.Marshal(b, m, deterministic)
}
func (m *ListSubmissionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSubmissionResponse.Merge(m, src)
}
func (m *ListSubmissionResponse) XXX_Size() int {
	return xxx_messageInfo_ListSubmissionResponse.Size(m)
}
func (m *ListSubmissionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSubmissionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListSubmissionResponse proto.InternalMessageInfo

func (m *ListSubmissionResponse) GetResults() []*Submission {
	if m != nil {
		return m.Results
	}
	return nil
}

type ReadSubmissionRequest struct {
	Id                   *types.UUIDValue `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ReadSubmissionRequest) Reset()         { *m = ReadSubmissionRequest{} }
func (m *ReadSubmissionRequest) String() string { return proto.CompactTextString(m) }
func (*ReadSubmissionRequest) ProtoMessage()    {}
func (*ReadSubmissionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f73f7111cf4d69d9, []int{5}
}

func (m *ReadSubmissionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadSubmissionRequest.Unmarshal(m, b)
}
func (m *ReadSubmissionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadSubmissionRequest.Marshal(b, m, deterministic)
}
func (m *ReadSubmissionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadSubmissionRequest.Merge(m, src)
}
func (m *ReadSubmissionRequest) XXX_Size() int {
	return xxx_messageInfo_ReadSubmissionRequest.Size(m)
}
func (m *ReadSubmissionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadSubmissionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadSubmissionRequest proto.InternalMessageInfo

func (m *ReadSubmissionRequest) GetId() *types.UUIDValue {
	if m != nil {
		return m.Id
	}
	return nil
}

type ReadSubmissionResponse struct {
	Result               *Submission `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ReadSubmissionResponse) Reset()         { *m = ReadSubmissionResponse{} }
func (m *ReadSubmissionResponse) String() string { return proto.CompactTextString(m) }
func (*ReadSubmissionResponse) ProtoMessage()    {}
func (*ReadSubmissionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f73f7111cf4d69d9, []int{6}
}

func (m *ReadSubmissionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadSubmissionResponse.Unmarshal(m, b)
}
func (m *ReadSubmissionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadSubmissionResponse.Marshal(b, m, deterministic)
}
func (m *ReadSubmissionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadSubmissionResponse.Merge(m, src)
}
func (m *ReadSubmissionResponse) XXX_Size() int {
	return xxx_messageInfo_ReadSubmissionResponse.Size(m)
}
func (m *ReadSubmissionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadSubmissionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadSubmissionResponse proto.InternalMessageInfo

func (m *ReadSubmissionResponse) GetResult() *Submission {
	if m != nil {
		return m.Result
	}
	return nil
}

type UpdateSubmissionRequest struct {
	Payload              *Submission `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UpdateSubmissionRequest) Reset()         { *m = UpdateSubmissionRequest{} }
func (m *UpdateSubmissionRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateSubmissionRequest) ProtoMessage()    {}
func (*UpdateSubmissionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f73f7111cf4d69d9, []int{7}
}

func (m *UpdateSubmissionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateSubmissionRequest.Unmarshal(m, b)
}
func (m *UpdateSubmissionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateSubmissionRequest.Marshal(b, m, deterministic)
}
func (m *UpdateSubmissionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateSubmissionRequest.Merge(m, src)
}
func (m *UpdateSubmissionRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateSubmissionRequest.Size(m)
}
func (m *UpdateSubmissionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateSubmissionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateSubmissionRequest proto.InternalMessageInfo

func (m *UpdateSubmissionRequest) GetPayload() *Submission {
	if m != nil {
		return m.Payload
	}
	return nil
}

type UpdateSubmissionResponse struct {
	Result               *Submission `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UpdateSubmissionResponse) Reset()         { *m = UpdateSubmissionResponse{} }
func (m *UpdateSubmissionResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateSubmissionResponse) ProtoMessage()    {}
func (*UpdateSubmissionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f73f7111cf4d69d9, []int{8}
}

func (m *UpdateSubmissionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateSubmissionResponse.Unmarshal(m, b)
}
func (m *UpdateSubmissionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateSubmissionResponse.Marshal(b, m, deterministic)
}
func (m *UpdateSubmissionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateSubmissionResponse.Merge(m, src)
}
func (m *UpdateSubmissionResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateSubmissionResponse.Size(m)
}
func (m *UpdateSubmissionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateSubmissionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateSubmissionResponse proto.InternalMessageInfo

func (m *UpdateSubmissionResponse) GetResult() *Submission {
	if m != nil {
		return m.Result
	}
	return nil
}

func init() {
	proto.RegisterType((*Submission)(nil), "service.Submission")
	proto.RegisterType((*CreateSubmissionRequest)(nil), "service.CreateSubmissionRequest")
	proto.RegisterType((*CreateSubmissionResponse)(nil), "service.CreateSubmissionResponse")
	proto.RegisterType((*ListSubmissionRequest)(nil), "service.ListSubmissionRequest")
	proto.RegisterType((*ListSubmissionResponse)(nil), "service.ListSubmissionResponse")
	proto.RegisterType((*ReadSubmissionRequest)(nil), "service.ReadSubmissionRequest")
	proto.RegisterType((*ReadSubmissionResponse)(nil), "service.ReadSubmissionResponse")
	proto.RegisterType((*UpdateSubmissionRequest)(nil), "service.UpdateSubmissionRequest")
	proto.RegisterType((*UpdateSubmissionResponse)(nil), "service.UpdateSubmissionResponse")
}

func init() {
	proto.RegisterFile("github.com/brocwoodworthIBLX/hack-db/pkg/pb/service.proto", fileDescriptor_f73f7111cf4d69d9)
}

var fileDescriptor_f73f7111cf4d69d9 = []byte{
	// 715 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xdd, 0x4e, 0xdb, 0x30,
	0x18, 0x55, 0x4a, 0x49, 0x3b, 0x17, 0x4d, 0x93, 0x07, 0x34, 0x54, 0x08, 0x4a, 0x24, 0x24, 0x24,
	0x96, 0x18, 0x75, 0xbb, 0x81, 0x49, 0xbb, 0xe8, 0x7e, 0x80, 0x89, 0x8b, 0x29, 0x88, 0x69, 0x9a,
	0x34, 0x21, 0x27, 0x31, 0xa9, 0x45, 0x88, 0x8d, 0xed, 0xc2, 0x3a, 0xb4, 0x9b, 0xbd, 0xc2, 0x9e,
	0x06, 0x2e, 0x76, 0xb7, 0x27, 0xd8, 0x1b, 0x4c, 0x7b, 0x90, 0x29, 0x4e, 0xda, 0x06, 0xda, 0x22,
	0x86, 0x76, 0xd3, 0xd6, 0xfe, 0xce, 0x77, 0xce, 0xf7, 0x73, 0x92, 0x82, 0xcd, 0x88, 0xaa, 0x4e,
	0xd7, 0x77, 0x03, 0x76, 0x82, 0x7c, 0xc1, 0x82, 0x73, 0xc6, 0xc2, 0x73, 0x26, 0x54, 0x67, 0xb7,
	0xbd, 0xf7, 0x01, 0x75, 0x70, 0x70, 0xec, 0x84, 0x3e, 0xe2, 0xc7, 0x11, 0xe2, 0x3e, 0x92, 0x44,
	0x9c, 0xd1, 0x80, 0xb8, 0x5c, 0x30, 0xc5, 0x60, 0x25, 0x3f, 0x36, 0x16, 0x23, 0xc6, 0xa2, 0x98,
	0x20, 0xcc, 0x29, 0xc2, 0x49, 0xc2, 0x14, 0x56, 0x94, 0x25, 0x32, 0x83, 0x35, 0x9e, 0xe8, 0xaf,
	0xc0, 0x89, 0x48, 0xe2, 0xc8, 0x73, 0x1c, 0x45, 0x44, 0x20, 0xc6, 0x35, 0x62, 0x0c, 0xfa, 0x6d,
	0xa1, 0x1e, 0x9a, 0x1c, 0x31, 0x3f, 0x66, 0x9f, 0x19, 0x27, 0x09, 0xc2, 0x2a, 0xc6, 0xd2, 0xc1,
	0x9c, 0x3b, 0x8a, 0xb1, 0xf8, 0x98, 0x2a, 0x74, 0xda, 0x25, 0xa2, 0x87, 0x02, 0x16, 0xc7, 0x24,
	0x48, 0x29, 0x0e, 0x19, 0x27, 0x02, 0x2b, 0x26, 0xfa, 0x5c, 0x5b, 0x93, 0xb8, 0x0a, 0x15, 0x45,
	0x4c, 0x9c, 0x0c, 0xca, 0x49, 0x0f, 0x79, 0xee, 0xe6, 0x5d, 0x73, 0x55, 0x8f, 0x13, 0x99, 0x7d,
	0x66, 0xa9, 0xf6, 0x0f, 0x03, 0x80, 0xfd, 0xae, 0x7f, 0x42, 0xa5, 0xa4, 0x2c, 0x81, 0xab, 0xa0,
	0x44, 0x43, 0xcb, 0x68, 0x1a, 0x6b, 0xb5, 0xd6, 0x9c, 0xab, 0x25, 0x32, 0xf4, 0xc1, 0xc1, 0xee,
	0xab, 0xf7, 0x38, 0xee, 0x12, 0xaf, 0x44, 0x43, 0x38, 0x0b, 0xa6, 0x15, 0x55, 0x31, 0xb1, 0x4a,
	0x4d, 0x63, 0xed, 0x81, 0x97, 0x1d, 0xe0, 0x12, 0x00, 0x72, 0x40, 0x65, 0x4d, 0xe9, 0x50, 0xe1,
	0x06, 0xae, 0x80, 0x19, 0x7d, 0x52, 0x8a, 0x84, 0x87, 0x7e, 0xcf, 0x2a, 0x6b, 0x44, 0x6d, 0x70,
	0xd7, 0xee, 0x41, 0x08, 0xca, 0x0a, 0x47, 0xd2, 0x9a, 0xd6, 0x21, 0xfd, 0x3b, 0x15, 0x3b, 0x63,
	0x8a, 0x48, 0xcb, 0x6c, 0x1a, 0x6b, 0xd3, 0x5e, 0x76, 0xd8, 0x32, 0xaf, 0x2e, 0x17, 0x4a, 0x55,
	0xc3, 0xde, 0x01, 0xf5, 0x97, 0x82, 0x60, 0x45, 0x86, 0x5d, 0x78, 0xe4, 0xb4, 0x4b, 0xa4, 0x82,
	0x0e, 0xa8, 0x70, 0xdc, 0x8b, 0x19, 0xee, 0x77, 0xf4, 0xd8, 0xed, 0x9b, 0xa2, 0x00, 0xee, 0x63,
	0xec, 0x6d, 0x60, 0x8d, 0x32, 0x49, 0xce, 0x12, 0x49, 0xe0, 0x3a, 0x30, 0x05, 0x91, 0xdd, 0x58,
	0xdd, 0xc6, 0x94, 0x43, 0xec, 0xdf, 0x06, 0x98, 0xdb, 0xa3, 0x52, 0x8d, 0x56, 0x84, 0x80, 0x79,
	0x44, 0x63, 0x45, 0x44, 0x4e, 0x53, 0x77, 0xfb, 0xeb, 0x72, 0x31, 0xa7, 0xee, 0x1b, 0x1d, 0xa3,
	0x49, 0xe4, 0xe5, 0x30, 0xb8, 0x01, 0xaa, 0x4c, 0x84, 0x44, 0xa4, 0xe3, 0x2a, 0xe5, 0x5b, 0xb9,
	0x96, 0xb2, 0xcf, 0x84, 0x4a, 0x13, 0x2a, 0x1a, 0xd6, 0xee, 0xc1, 0x67, 0xa9, 0x04, 0x89, 0x43,
	0xa9, 0x17, 0x50, 0x6b, 0x2d, 0xde, 0x94, 0x20, 0x71, 0xb8, 0x4f, 0x72, 0x17, 0x7a, 0x39, 0x16,
	0x6e, 0x00, 0x93, 0xe3, 0x88, 0x26, 0x91, 0x5e, 0x4a, 0xad, 0x65, 0x5d, 0xcf, 0x7a, 0x97, 0xc6,
	0x70, 0x96, 0x91, 0xe1, 0xec, 0x6d, 0x30, 0x7f, 0xb3, 0xc7, 0x7c, 0x56, 0x0e, 0xa8, 0x64, 0x83,
	0x90, 0x96, 0xd1, 0x9c, 0x9a, 0x38, 0xf6, 0x1c, 0x63, 0xbf, 0x00, 0x73, 0x1e, 0xc1, 0xe1, 0xe8,
	0xb0, 0xee, 0xe6, 0x45, 0xfb, 0x35, 0x98, 0xbf, 0x99, 0x7f, 0x9f, 0xa5, 0xed, 0x80, 0xfa, 0x01,
	0x0f, 0xff, 0x93, 0x8f, 0x46, 0x99, 0xee, 0x51, 0x52, 0xeb, 0xe7, 0x14, 0xa8, 0x0d, 0xaf, 0x25,
	0x8c, 0x80, 0x99, 0x19, 0x14, 0x36, 0x07, 0x69, 0x13, 0xbc, 0xdf, 0x58, 0xb9, 0x05, 0x91, 0xd5,
	0x62, 0x5b, 0xdf, 0x7e, 0xfd, 0xf9, 0x5e, 0x82, 0x76, 0x05, 0x65, 0x4f, 0xe0, 0x56, 0xbf, 0x03,
	0xf8, 0x05, 0x98, 0x59, 0x07, 0x05, 0xa1, 0x09, 0xc3, 0x29, 0x08, 0x4d, 0x6a, 0xda, 0x5e, 0xd7,
	0x42, 0xab, 0xad, 0x46, 0x2e, 0x84, 0x2e, 0x72, 0x21, 0x97, 0x86, 0xee, 0x59, 0xba, 0xc8, 0xaf,
	0x43, 0xed, 0x0e, 0x28, 0xa7, 0xeb, 0x84, 0x4b, 0x03, 0xde, 0xb1, 0xee, 0x68, 0x2c, 0x4f, 0x8c,
	0xe7, 0xaa, 0xcb, 0x5a, 0x75, 0x01, 0xd6, 0xd1, 0xf0, 0x15, 0x24, 0xd1, 0xc5, 0x40, 0x12, 0x7e,
	0x02, 0xe5, 0xd4, 0xc1, 0x05, 0xa5, 0xb1, 0x0f, 0x6d, 0x41, 0x69, 0xbc, 0xe1, 0xed, 0x59, 0xad,
	0xf4, 0x10, 0xce, 0x14, 0x95, 0x1a, 0xd5, 0xab, 0xcb, 0x85, 0x72, 0xd5, 0x78, 0x64, 0xb4, 0x37,
	0x3e, 0xba, 0xff, 0xf0, 0xc7, 0xf5, 0x9c, 0xfb, 0xbe, 0xa9, 0x5f, 0xce, 0x4f, 0xff, 0x06, 0x00,
	0x00, 0xff, 0xff, 0x37, 0xe2, 0xb0, 0xfd, 0xf1, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SubmissionsClient is the client API for Submissions service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SubmissionsClient interface {
	Create(ctx context.Context, in *CreateSubmissionRequest, opts ...grpc.CallOption) (*CreateSubmissionResponse, error)
	Update(ctx context.Context, in *UpdateSubmissionRequest, opts ...grpc.CallOption) (*UpdateSubmissionResponse, error)
	Read(ctx context.Context, in *ReadSubmissionRequest, opts ...grpc.CallOption) (*ReadSubmissionResponse, error)
	List(ctx context.Context, in *ListSubmissionRequest, opts ...grpc.CallOption) (*ListSubmissionResponse, error)
}

type submissionsClient struct {
	cc *grpc.ClientConn
}

func NewSubmissionsClient(cc *grpc.ClientConn) SubmissionsClient {
	return &submissionsClient{cc}
}

func (c *submissionsClient) Create(ctx context.Context, in *CreateSubmissionRequest, opts ...grpc.CallOption) (*CreateSubmissionResponse, error) {
	out := new(CreateSubmissionResponse)
	err := c.cc.Invoke(ctx, "/service.Submissions/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *submissionsClient) Update(ctx context.Context, in *UpdateSubmissionRequest, opts ...grpc.CallOption) (*UpdateSubmissionResponse, error) {
	out := new(UpdateSubmissionResponse)
	err := c.cc.Invoke(ctx, "/service.Submissions/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *submissionsClient) Read(ctx context.Context, in *ReadSubmissionRequest, opts ...grpc.CallOption) (*ReadSubmissionResponse, error) {
	out := new(ReadSubmissionResponse)
	err := c.cc.Invoke(ctx, "/service.Submissions/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *submissionsClient) List(ctx context.Context, in *ListSubmissionRequest, opts ...grpc.CallOption) (*ListSubmissionResponse, error) {
	out := new(ListSubmissionResponse)
	err := c.cc.Invoke(ctx, "/service.Submissions/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SubmissionsServer is the server API for Submissions service.
type SubmissionsServer interface {
	Create(context.Context, *CreateSubmissionRequest) (*CreateSubmissionResponse, error)
	Update(context.Context, *UpdateSubmissionRequest) (*UpdateSubmissionResponse, error)
	Read(context.Context, *ReadSubmissionRequest) (*ReadSubmissionResponse, error)
	List(context.Context, *ListSubmissionRequest) (*ListSubmissionResponse, error)
}

func RegisterSubmissionsServer(s *grpc.Server, srv SubmissionsServer) {
	s.RegisterService(&_Submissions_serviceDesc, srv)
}

func _Submissions_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSubmissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubmissionsServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Submissions/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubmissionsServer).Create(ctx, req.(*CreateSubmissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Submissions_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSubmissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubmissionsServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Submissions/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubmissionsServer).Update(ctx, req.(*UpdateSubmissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Submissions_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadSubmissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubmissionsServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Submissions/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubmissionsServer).Read(ctx, req.(*ReadSubmissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Submissions_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSubmissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubmissionsServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Submissions/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubmissionsServer).List(ctx, req.(*ListSubmissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Submissions_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.Submissions",
	HandlerType: (*SubmissionsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Submissions_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Submissions_Update_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _Submissions_Read_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Submissions_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/brocwoodworthIBLX/hack-db/pkg/pb/service.proto",
}
