// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/brocwoodworthIBLX/hack-db/pkg/pb/service.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	query "github.com/infobloxopen/atlas-app-toolkit/query"
	_ "github.com/infobloxopen/protoc-gen-gorm/options"
	types "github.com/infobloxopen/protoc-gen-gorm/types"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Tool struct {
	Id                   *types.UUIDValue `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string           `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	ToolCode             string           `protobuf:"bytes,3,opt,name=tool_code,json=toolCode,proto3" json:"tool_code,omitempty"`
	CreatedBy            string           `protobuf:"bytes,4,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	Description          string           `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Tags                 []string         `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	VoteCount            int32            `protobuf:"varint,7,opt,name=vote_count,json=voteCount,proto3" json:"vote_count,omitempty"`
	BrokenCount          int32            `protobuf:"varint,8,opt,name=broken_count,json=brokenCount,proto3" json:"broken_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Tool) Reset()         { *m = Tool{} }
func (m *Tool) String() string { return proto.CompactTextString(m) }
func (*Tool) ProtoMessage()    {}
func (*Tool) Descriptor() ([]byte, []int) {
	return fileDescriptor_f73f7111cf4d69d9, []int{0}
}

func (m *Tool) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tool.Unmarshal(m, b)
}
func (m *Tool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tool.Marshal(b, m, deterministic)
}
func (m *Tool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tool.Merge(m, src)
}
func (m *Tool) XXX_Size() int {
	return xxx_messageInfo_Tool.Size(m)
}
func (m *Tool) XXX_DiscardUnknown() {
	xxx_messageInfo_Tool.DiscardUnknown(m)
}

var xxx_messageInfo_Tool proto.InternalMessageInfo

func (m *Tool) GetId() *types.UUIDValue {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Tool) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Tool) GetToolCode() string {
	if m != nil {
		return m.ToolCode
	}
	return ""
}

func (m *Tool) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *Tool) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Tool) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Tool) GetVoteCount() int32 {
	if m != nil {
		return m.VoteCount
	}
	return 0
}

func (m *Tool) GetBrokenCount() int32 {
	if m != nil {
		return m.BrokenCount
	}
	return 0
}

type Tag struct {
	Id                   *types.UUIDValue   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string             `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ToolId               []*types.UUIDValue `protobuf:"bytes,3,rep,name=tool_id,json=toolId,proto3" json:"tool_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Tag) Reset()         { *m = Tag{} }
func (m *Tag) String() string { return proto.CompactTextString(m) }
func (*Tag) ProtoMessage()    {}
func (*Tag) Descriptor() ([]byte, []int) {
	return fileDescriptor_f73f7111cf4d69d9, []int{1}
}

func (m *Tag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tag.Unmarshal(m, b)
}
func (m *Tag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tag.Marshal(b, m, deterministic)
}
func (m *Tag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tag.Merge(m, src)
}
func (m *Tag) XXX_Size() int {
	return xxx_messageInfo_Tag.Size(m)
}
func (m *Tag) XXX_DiscardUnknown() {
	xxx_messageInfo_Tag.DiscardUnknown(m)
}

var xxx_messageInfo_Tag proto.InternalMessageInfo

func (m *Tag) GetId() *types.UUIDValue {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Tag) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Tag) GetToolId() []*types.UUIDValue {
	if m != nil {
		return m.ToolId
	}
	return nil
}

type Comment struct {
	Id                   *types.UUIDValue `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Comment              string           `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	CreatedBy            string           `protobuf:"bytes,3,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	ToolId               *types.UUIDValue `protobuf:"bytes,4,opt,name=tool_id,json=toolId,proto3" json:"tool_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Comment) Reset()         { *m = Comment{} }
func (m *Comment) String() string { return proto.CompactTextString(m) }
func (*Comment) ProtoMessage()    {}
func (*Comment) Descriptor() ([]byte, []int) {
	return fileDescriptor_f73f7111cf4d69d9, []int{2}
}

func (m *Comment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Comment.Unmarshal(m, b)
}
func (m *Comment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Comment.Marshal(b, m, deterministic)
}
func (m *Comment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Comment.Merge(m, src)
}
func (m *Comment) XXX_Size() int {
	return xxx_messageInfo_Comment.Size(m)
}
func (m *Comment) XXX_DiscardUnknown() {
	xxx_messageInfo_Comment.DiscardUnknown(m)
}

var xxx_messageInfo_Comment proto.InternalMessageInfo

func (m *Comment) GetId() *types.UUIDValue {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Comment) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *Comment) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *Comment) GetToolId() *types.UUIDValue {
	if m != nil {
		return m.ToolId
	}
	return nil
}

type CreateToolRequest struct {
	Payload              *Tool    `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateToolRequest) Reset()         { *m = CreateToolRequest{} }
func (m *CreateToolRequest) String() string { return proto.CompactTextString(m) }
func (*CreateToolRequest) ProtoMessage()    {}
func (*CreateToolRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f73f7111cf4d69d9, []int{3}
}

func (m *CreateToolRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateToolRequest.Unmarshal(m, b)
}
func (m *CreateToolRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateToolRequest.Marshal(b, m, deterministic)
}
func (m *CreateToolRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateToolRequest.Merge(m, src)
}
func (m *CreateToolRequest) XXX_Size() int {
	return xxx_messageInfo_CreateToolRequest.Size(m)
}
func (m *CreateToolRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateToolRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateToolRequest proto.InternalMessageInfo

func (m *CreateToolRequest) GetPayload() *Tool {
	if m != nil {
		return m.Payload
	}
	return nil
}

type CreateToolResponse struct {
	Result               *Tool    `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateToolResponse) Reset()         { *m = CreateToolResponse{} }
func (m *CreateToolResponse) String() string { return proto.CompactTextString(m) }
func (*CreateToolResponse) ProtoMessage()    {}
func (*CreateToolResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f73f7111cf4d69d9, []int{4}
}

func (m *CreateToolResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateToolResponse.Unmarshal(m, b)
}
func (m *CreateToolResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateToolResponse.Marshal(b, m, deterministic)
}
func (m *CreateToolResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateToolResponse.Merge(m, src)
}
func (m *CreateToolResponse) XXX_Size() int {
	return xxx_messageInfo_CreateToolResponse.Size(m)
}
func (m *CreateToolResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateToolResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateToolResponse proto.InternalMessageInfo

func (m *CreateToolResponse) GetResult() *Tool {
	if m != nil {
		return m.Result
	}
	return nil
}

type ListToolRequest struct {
	Filter               *query.Filtering      `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	OrderBy              *query.Sorting        `protobuf:"bytes,2,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	Fields               *query.FieldSelection `protobuf:"bytes,3,opt,name=fields,proto3" json:"fields,omitempty"`
	Paging               *query.Pagination     `protobuf:"bytes,4,opt,name=paging,proto3" json:"paging,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ListToolRequest) Reset()         { *m = ListToolRequest{} }
func (m *ListToolRequest) String() string { return proto.CompactTextString(m) }
func (*ListToolRequest) ProtoMessage()    {}
func (*ListToolRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f73f7111cf4d69d9, []int{5}
}

func (m *ListToolRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListToolRequest.Unmarshal(m, b)
}
func (m *ListToolRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListToolRequest.Marshal(b, m, deterministic)
}
func (m *ListToolRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListToolRequest.Merge(m, src)
}
func (m *ListToolRequest) XXX_Size() int {
	return xxx_messageInfo_ListToolRequest.Size(m)
}
func (m *ListToolRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListToolRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListToolRequest proto.InternalMessageInfo

func (m *ListToolRequest) GetFilter() *query.Filtering {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *ListToolRequest) GetOrderBy() *query.Sorting {
	if m != nil {
		return m.OrderBy
	}
	return nil
}

func (m *ListToolRequest) GetFields() *query.FieldSelection {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *ListToolRequest) GetPaging() *query.Pagination {
	if m != nil {
		return m.Paging
	}
	return nil
}

type ListToolResponse struct {
	Results              []*Tool  `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListToolResponse) Reset()         { *m = ListToolResponse{} }
func (m *ListToolResponse) String() string { return proto.CompactTextString(m) }
func (*ListToolResponse) ProtoMessage()    {}
func (*ListToolResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f73f7111cf4d69d9, []int{6}
}

func (m *ListToolResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListToolResponse.Unmarshal(m, b)
}
func (m *ListToolResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListToolResponse.Marshal(b, m, deterministic)
}
func (m *ListToolResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListToolResponse.Merge(m, src)
}
func (m *ListToolResponse) XXX_Size() int {
	return xxx_messageInfo_ListToolResponse.Size(m)
}
func (m *ListToolResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListToolResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListToolResponse proto.InternalMessageInfo

func (m *ListToolResponse) GetResults() []*Tool {
	if m != nil {
		return m.Results
	}
	return nil
}

type ReadToolRequest struct {
	Id                   *types.UUIDValue `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ReadToolRequest) Reset()         { *m = ReadToolRequest{} }
func (m *ReadToolRequest) String() string { return proto.CompactTextString(m) }
func (*ReadToolRequest) ProtoMessage()    {}
func (*ReadToolRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f73f7111cf4d69d9, []int{7}
}

func (m *ReadToolRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadToolRequest.Unmarshal(m, b)
}
func (m *ReadToolRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadToolRequest.Marshal(b, m, deterministic)
}
func (m *ReadToolRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadToolRequest.Merge(m, src)
}
func (m *ReadToolRequest) XXX_Size() int {
	return xxx_messageInfo_ReadToolRequest.Size(m)
}
func (m *ReadToolRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadToolRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadToolRequest proto.InternalMessageInfo

func (m *ReadToolRequest) GetId() *types.UUIDValue {
	if m != nil {
		return m.Id
	}
	return nil
}

type ReadToolResponse struct {
	Result               *Tool    `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadToolResponse) Reset()         { *m = ReadToolResponse{} }
func (m *ReadToolResponse) String() string { return proto.CompactTextString(m) }
func (*ReadToolResponse) ProtoMessage()    {}
func (*ReadToolResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f73f7111cf4d69d9, []int{8}
}

func (m *ReadToolResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadToolResponse.Unmarshal(m, b)
}
func (m *ReadToolResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadToolResponse.Marshal(b, m, deterministic)
}
func (m *ReadToolResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadToolResponse.Merge(m, src)
}
func (m *ReadToolResponse) XXX_Size() int {
	return xxx_messageInfo_ReadToolResponse.Size(m)
}
func (m *ReadToolResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadToolResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadToolResponse proto.InternalMessageInfo

func (m *ReadToolResponse) GetResult() *Tool {
	if m != nil {
		return m.Result
	}
	return nil
}

type UpdateToolRequest struct {
	Payload              *Tool    `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateToolRequest) Reset()         { *m = UpdateToolRequest{} }
func (m *UpdateToolRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateToolRequest) ProtoMessage()    {}
func (*UpdateToolRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f73f7111cf4d69d9, []int{9}
}

func (m *UpdateToolRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateToolRequest.Unmarshal(m, b)
}
func (m *UpdateToolRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateToolRequest.Marshal(b, m, deterministic)
}
func (m *UpdateToolRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateToolRequest.Merge(m, src)
}
func (m *UpdateToolRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateToolRequest.Size(m)
}
func (m *UpdateToolRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateToolRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateToolRequest proto.InternalMessageInfo

func (m *UpdateToolRequest) GetPayload() *Tool {
	if m != nil {
		return m.Payload
	}
	return nil
}

type UpdateToolResponse struct {
	Result               *Tool    `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateToolResponse) Reset()         { *m = UpdateToolResponse{} }
func (m *UpdateToolResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateToolResponse) ProtoMessage()    {}
func (*UpdateToolResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f73f7111cf4d69d9, []int{10}
}

func (m *UpdateToolResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateToolResponse.Unmarshal(m, b)
}
func (m *UpdateToolResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateToolResponse.Marshal(b, m, deterministic)
}
func (m *UpdateToolResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateToolResponse.Merge(m, src)
}
func (m *UpdateToolResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateToolResponse.Size(m)
}
func (m *UpdateToolResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateToolResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateToolResponse proto.InternalMessageInfo

func (m *UpdateToolResponse) GetResult() *Tool {
	if m != nil {
		return m.Result
	}
	return nil
}

type CreateTagRequest struct {
	Payload              *Tag     `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTagRequest) Reset()         { *m = CreateTagRequest{} }
func (m *CreateTagRequest) String() string { return proto.CompactTextString(m) }
func (*CreateTagRequest) ProtoMessage()    {}
func (*CreateTagRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f73f7111cf4d69d9, []int{11}
}

func (m *CreateTagRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTagRequest.Unmarshal(m, b)
}
func (m *CreateTagRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTagRequest.Marshal(b, m, deterministic)
}
func (m *CreateTagRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTagRequest.Merge(m, src)
}
func (m *CreateTagRequest) XXX_Size() int {
	return xxx_messageInfo_CreateTagRequest.Size(m)
}
func (m *CreateTagRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTagRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTagRequest proto.InternalMessageInfo

func (m *CreateTagRequest) GetPayload() *Tag {
	if m != nil {
		return m.Payload
	}
	return nil
}

type CreateTagResponse struct {
	Result               *Tag     `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTagResponse) Reset()         { *m = CreateTagResponse{} }
func (m *CreateTagResponse) String() string { return proto.CompactTextString(m) }
func (*CreateTagResponse) ProtoMessage()    {}
func (*CreateTagResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f73f7111cf4d69d9, []int{12}
}

func (m *CreateTagResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTagResponse.Unmarshal(m, b)
}
func (m *CreateTagResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTagResponse.Marshal(b, m, deterministic)
}
func (m *CreateTagResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTagResponse.Merge(m, src)
}
func (m *CreateTagResponse) XXX_Size() int {
	return xxx_messageInfo_CreateTagResponse.Size(m)
}
func (m *CreateTagResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTagResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTagResponse proto.InternalMessageInfo

func (m *CreateTagResponse) GetResult() *Tag {
	if m != nil {
		return m.Result
	}
	return nil
}

type ListTagRequest struct {
	Filter               *query.Filtering      `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	OrderBy              *query.Sorting        `protobuf:"bytes,2,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	Fields               *query.FieldSelection `protobuf:"bytes,3,opt,name=fields,proto3" json:"fields,omitempty"`
	Paging               *query.Pagination     `protobuf:"bytes,4,opt,name=paging,proto3" json:"paging,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ListTagRequest) Reset()         { *m = ListTagRequest{} }
func (m *ListTagRequest) String() string { return proto.CompactTextString(m) }
func (*ListTagRequest) ProtoMessage()    {}
func (*ListTagRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f73f7111cf4d69d9, []int{13}
}

func (m *ListTagRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTagRequest.Unmarshal(m, b)
}
func (m *ListTagRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTagRequest.Marshal(b, m, deterministic)
}
func (m *ListTagRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTagRequest.Merge(m, src)
}
func (m *ListTagRequest) XXX_Size() int {
	return xxx_messageInfo_ListTagRequest.Size(m)
}
func (m *ListTagRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTagRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListTagRequest proto.InternalMessageInfo

func (m *ListTagRequest) GetFilter() *query.Filtering {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *ListTagRequest) GetOrderBy() *query.Sorting {
	if m != nil {
		return m.OrderBy
	}
	return nil
}

func (m *ListTagRequest) GetFields() *query.FieldSelection {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *ListTagRequest) GetPaging() *query.Pagination {
	if m != nil {
		return m.Paging
	}
	return nil
}

type ListTagResponse struct {
	Results              []*Tag   `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListTagResponse) Reset()         { *m = ListTagResponse{} }
func (m *ListTagResponse) String() string { return proto.CompactTextString(m) }
func (*ListTagResponse) ProtoMessage()    {}
func (*ListTagResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f73f7111cf4d69d9, []int{14}
}

func (m *ListTagResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTagResponse.Unmarshal(m, b)
}
func (m *ListTagResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTagResponse.Marshal(b, m, deterministic)
}
func (m *ListTagResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTagResponse.Merge(m, src)
}
func (m *ListTagResponse) XXX_Size() int {
	return xxx_messageInfo_ListTagResponse.Size(m)
}
func (m *ListTagResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTagResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListTagResponse proto.InternalMessageInfo

func (m *ListTagResponse) GetResults() []*Tag {
	if m != nil {
		return m.Results
	}
	return nil
}

type ReadTagRequest struct {
	Id                   *types.UUIDValue `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ReadTagRequest) Reset()         { *m = ReadTagRequest{} }
func (m *ReadTagRequest) String() string { return proto.CompactTextString(m) }
func (*ReadTagRequest) ProtoMessage()    {}
func (*ReadTagRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f73f7111cf4d69d9, []int{15}
}

func (m *ReadTagRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadTagRequest.Unmarshal(m, b)
}
func (m *ReadTagRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadTagRequest.Marshal(b, m, deterministic)
}
func (m *ReadTagRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadTagRequest.Merge(m, src)
}
func (m *ReadTagRequest) XXX_Size() int {
	return xxx_messageInfo_ReadTagRequest.Size(m)
}
func (m *ReadTagRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadTagRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadTagRequest proto.InternalMessageInfo

func (m *ReadTagRequest) GetId() *types.UUIDValue {
	if m != nil {
		return m.Id
	}
	return nil
}

type ReadTagResponse struct {
	Result               *Tag     `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadTagResponse) Reset()         { *m = ReadTagResponse{} }
func (m *ReadTagResponse) String() string { return proto.CompactTextString(m) }
func (*ReadTagResponse) ProtoMessage()    {}
func (*ReadTagResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f73f7111cf4d69d9, []int{16}
}

func (m *ReadTagResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadTagResponse.Unmarshal(m, b)
}
func (m *ReadTagResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadTagResponse.Marshal(b, m, deterministic)
}
func (m *ReadTagResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadTagResponse.Merge(m, src)
}
func (m *ReadTagResponse) XXX_Size() int {
	return xxx_messageInfo_ReadTagResponse.Size(m)
}
func (m *ReadTagResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadTagResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadTagResponse proto.InternalMessageInfo

func (m *ReadTagResponse) GetResult() *Tag {
	if m != nil {
		return m.Result
	}
	return nil
}

type CreateCommentRequest struct {
	Payload              *Comment `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCommentRequest) Reset()         { *m = CreateCommentRequest{} }
func (m *CreateCommentRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCommentRequest) ProtoMessage()    {}
func (*CreateCommentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f73f7111cf4d69d9, []int{17}
}

func (m *CreateCommentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCommentRequest.Unmarshal(m, b)
}
func (m *CreateCommentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCommentRequest.Marshal(b, m, deterministic)
}
func (m *CreateCommentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCommentRequest.Merge(m, src)
}
func (m *CreateCommentRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCommentRequest.Size(m)
}
func (m *CreateCommentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCommentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCommentRequest proto.InternalMessageInfo

func (m *CreateCommentRequest) GetPayload() *Comment {
	if m != nil {
		return m.Payload
	}
	return nil
}

type CreateCommentResponse struct {
	Result               *Comment `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCommentResponse) Reset()         { *m = CreateCommentResponse{} }
func (m *CreateCommentResponse) String() string { return proto.CompactTextString(m) }
func (*CreateCommentResponse) ProtoMessage()    {}
func (*CreateCommentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f73f7111cf4d69d9, []int{18}
}

func (m *CreateCommentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCommentResponse.Unmarshal(m, b)
}
func (m *CreateCommentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCommentResponse.Marshal(b, m, deterministic)
}
func (m *CreateCommentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCommentResponse.Merge(m, src)
}
func (m *CreateCommentResponse) XXX_Size() int {
	return xxx_messageInfo_CreateCommentResponse.Size(m)
}
func (m *CreateCommentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCommentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCommentResponse proto.InternalMessageInfo

func (m *CreateCommentResponse) GetResult() *Comment {
	if m != nil {
		return m.Result
	}
	return nil
}

type ListCommentRequest struct {
	ToolId               *types.UUIDValue `protobuf:"bytes,1,opt,name=tool_id,json=toolId,proto3" json:"tool_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ListCommentRequest) Reset()         { *m = ListCommentRequest{} }
func (m *ListCommentRequest) String() string { return proto.CompactTextString(m) }
func (*ListCommentRequest) ProtoMessage()    {}
func (*ListCommentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f73f7111cf4d69d9, []int{19}
}

func (m *ListCommentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCommentRequest.Unmarshal(m, b)
}
func (m *ListCommentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCommentRequest.Marshal(b, m, deterministic)
}
func (m *ListCommentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCommentRequest.Merge(m, src)
}
func (m *ListCommentRequest) XXX_Size() int {
	return xxx_messageInfo_ListCommentRequest.Size(m)
}
func (m *ListCommentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCommentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListCommentRequest proto.InternalMessageInfo

func (m *ListCommentRequest) GetToolId() *types.UUIDValue {
	if m != nil {
		return m.ToolId
	}
	return nil
}

type ListCommentResponse struct {
	Results              []*Comment `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListCommentResponse) Reset()         { *m = ListCommentResponse{} }
func (m *ListCommentResponse) String() string { return proto.CompactTextString(m) }
func (*ListCommentResponse) ProtoMessage()    {}
func (*ListCommentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f73f7111cf4d69d9, []int{20}
}

func (m *ListCommentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCommentResponse.Unmarshal(m, b)
}
func (m *ListCommentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCommentResponse.Marshal(b, m, deterministic)
}
func (m *ListCommentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCommentResponse.Merge(m, src)
}
func (m *ListCommentResponse) XXX_Size() int {
	return xxx_messageInfo_ListCommentResponse.Size(m)
}
func (m *ListCommentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCommentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListCommentResponse proto.InternalMessageInfo

func (m *ListCommentResponse) GetResults() []*Comment {
	if m != nil {
		return m.Results
	}
	return nil
}

type ReadCommentRequest struct {
	Id                   *types.UUIDValue `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ReadCommentRequest) Reset()         { *m = ReadCommentRequest{} }
func (m *ReadCommentRequest) String() string { return proto.CompactTextString(m) }
func (*ReadCommentRequest) ProtoMessage()    {}
func (*ReadCommentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f73f7111cf4d69d9, []int{21}
}

func (m *ReadCommentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadCommentRequest.Unmarshal(m, b)
}
func (m *ReadCommentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadCommentRequest.Marshal(b, m, deterministic)
}
func (m *ReadCommentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadCommentRequest.Merge(m, src)
}
func (m *ReadCommentRequest) XXX_Size() int {
	return xxx_messageInfo_ReadCommentRequest.Size(m)
}
func (m *ReadCommentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadCommentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadCommentRequest proto.InternalMessageInfo

func (m *ReadCommentRequest) GetId() *types.UUIDValue {
	if m != nil {
		return m.Id
	}
	return nil
}

type ReadCommentResponse struct {
	Result               *Comment `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadCommentResponse) Reset()         { *m = ReadCommentResponse{} }
func (m *ReadCommentResponse) String() string { return proto.CompactTextString(m) }
func (*ReadCommentResponse) ProtoMessage()    {}
func (*ReadCommentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f73f7111cf4d69d9, []int{22}
}

func (m *ReadCommentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadCommentResponse.Unmarshal(m, b)
}
func (m *ReadCommentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadCommentResponse.Marshal(b, m, deterministic)
}
func (m *ReadCommentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadCommentResponse.Merge(m, src)
}
func (m *ReadCommentResponse) XXX_Size() int {
	return xxx_messageInfo_ReadCommentResponse.Size(m)
}
func (m *ReadCommentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadCommentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadCommentResponse proto.InternalMessageInfo

func (m *ReadCommentResponse) GetResult() *Comment {
	if m != nil {
		return m.Result
	}
	return nil
}

func init() {
	proto.RegisterType((*Tool)(nil), "service.Tool")
	proto.RegisterType((*Tag)(nil), "service.Tag")
	proto.RegisterType((*Comment)(nil), "service.Comment")
	proto.RegisterType((*CreateToolRequest)(nil), "service.CreateToolRequest")
	proto.RegisterType((*CreateToolResponse)(nil), "service.CreateToolResponse")
	proto.RegisterType((*ListToolRequest)(nil), "service.ListToolRequest")
	proto.RegisterType((*ListToolResponse)(nil), "service.ListToolResponse")
	proto.RegisterType((*ReadToolRequest)(nil), "service.ReadToolRequest")
	proto.RegisterType((*ReadToolResponse)(nil), "service.ReadToolResponse")
	proto.RegisterType((*UpdateToolRequest)(nil), "service.UpdateToolRequest")
	proto.RegisterType((*UpdateToolResponse)(nil), "service.UpdateToolResponse")
	proto.RegisterType((*CreateTagRequest)(nil), "service.CreateTagRequest")
	proto.RegisterType((*CreateTagResponse)(nil), "service.CreateTagResponse")
	proto.RegisterType((*ListTagRequest)(nil), "service.ListTagRequest")
	proto.RegisterType((*ListTagResponse)(nil), "service.ListTagResponse")
	proto.RegisterType((*ReadTagRequest)(nil), "service.ReadTagRequest")
	proto.RegisterType((*ReadTagResponse)(nil), "service.ReadTagResponse")
	proto.RegisterType((*CreateCommentRequest)(nil), "service.CreateCommentRequest")
	proto.RegisterType((*CreateCommentResponse)(nil), "service.CreateCommentResponse")
	proto.RegisterType((*ListCommentRequest)(nil), "service.ListCommentRequest")
	proto.RegisterType((*ListCommentResponse)(nil), "service.ListCommentResponse")
	proto.RegisterType((*ReadCommentRequest)(nil), "service.ReadCommentRequest")
	proto.RegisterType((*ReadCommentResponse)(nil), "service.ReadCommentResponse")
}

func init() {
	proto.RegisterFile("github.com/brocwoodworthIBLX/hack-db/pkg/pb/service.proto", fileDescriptor_f73f7111cf4d69d9)
}

var fileDescriptor_f73f7111cf4d69d9 = []byte{
	// 1129 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x57, 0xdd, 0x6e, 0xdc, 0x44,
	0x14, 0x96, 0x77, 0x37, 0xbb, 0x9b, 0x93, 0xb6, 0xd9, 0x4c, 0x1a, 0xe2, 0x38, 0x29, 0x5a, 0x0c,
	0x6d, 0x43, 0x45, 0xec, 0x28, 0x20, 0x95, 0x24, 0x95, 0x50, 0x93, 0x0a, 0x94, 0xaa, 0x17, 0x68,
	0x9b, 0x54, 0xc0, 0x05, 0xd1, 0xd8, 0x9e, 0x3a, 0x56, 0x1c, 0x8f, 0x6b, 0xcf, 0x26, 0x5d, 0x55,
	0xdc, 0x20, 0xf1, 0x04, 0x3c, 0x01, 0x8f, 0xd1, 0x4a, 0x3c, 0x05, 0x97, 0x70, 0xc9, 0x6b, 0x20,
	0xd0, 0x8c, 0xc7, 0x7f, 0x13, 0x07, 0x6d, 0xc4, 0x1d, 0x37, 0xc9, 0x7a, 0xce, 0xf9, 0xbe, 0xef,
	0x9c, 0x6f, 0xce, 0x8c, 0x77, 0x61, 0xdb, 0x0f, 0xd8, 0xc9, 0xd8, 0xb1, 0x5c, 0x7a, 0x66, 0x3b,
	0x09, 0x75, 0x2f, 0x28, 0xf5, 0x2e, 0x68, 0xc2, 0x4e, 0x0e, 0xf6, 0x9e, 0x7d, 0x63, 0x9f, 0x60,
	0xf7, 0x74, 0xc3, 0x73, 0xec, 0xf8, 0xd4, 0xb7, 0x63, 0xc7, 0x4e, 0x49, 0x72, 0x1e, 0xb8, 0xc4,
	0x8a, 0x13, 0xca, 0x28, 0xea, 0xc9, 0x47, 0x63, 0xcd, 0xa7, 0xd4, 0x0f, 0x89, 0x8d, 0xe3, 0xc0,
	0xc6, 0x51, 0x44, 0x19, 0x66, 0x01, 0x8d, 0xd2, 0x2c, 0xcd, 0xf8, 0x44, 0xfc, 0x73, 0x37, 0x7c,
	0x12, 0x6d, 0xa4, 0x17, 0xd8, 0xf7, 0x49, 0x62, 0xd3, 0x58, 0x64, 0x34, 0x64, 0x3f, 0xad, 0xd4,
	0x13, 0x44, 0x2f, 0xa9, 0x13, 0xd2, 0xd7, 0x34, 0x26, 0x91, 0x8d, 0x59, 0x88, 0xd3, 0x0d, 0x1c,
	0xc7, 0x1b, 0x8c, 0xd2, 0xf0, 0x34, 0x60, 0xf6, 0xab, 0x31, 0x49, 0x26, 0xb6, 0x4b, 0xc3, 0x90,
	0xb8, 0x9c, 0xe2, 0x98, 0xc6, 0x24, 0xc1, 0x8c, 0x26, 0x39, 0xd7, 0xce, 0x55, 0x5c, 0x95, 0x8a,
	0x7c, 0x9a, 0x9c, 0x15, 0xe5, 0xf0, 0x07, 0x89, 0xdd, 0x9e, 0x16, 0xcb, 0x26, 0x31, 0x49, 0xb3,
	0xbf, 0x19, 0xd4, 0xfc, 0x5b, 0x83, 0xce, 0x21, 0xa5, 0x21, 0xba, 0x0b, 0xad, 0xc0, 0xd3, 0xb5,
	0xa1, 0xb6, 0x3e, 0xb7, 0xb5, 0x64, 0x09, 0xf2, 0x2c, 0xef, 0xe8, 0xe8, 0xe0, 0xc9, 0x0b, 0x1c,
	0x8e, 0xc9, 0xa8, 0x15, 0x78, 0xe8, 0x36, 0xcc, 0xb0, 0x80, 0x85, 0x44, 0x6f, 0x0d, 0xb5, 0xf5,
	0xd9, 0x51, 0xf6, 0x80, 0x56, 0x61, 0x96, 0x37, 0x7a, 0xec, 0x52, 0x8f, 0xe8, 0x6d, 0x11, 0xe9,
	0xf3, 0x85, 0x7d, 0xea, 0x11, 0x74, 0x07, 0xc0, 0x4d, 0x08, 0x66, 0xc4, 0x3b, 0x76, 0x26, 0x7a,
	0x47, 0x44, 0x67, 0xe5, 0xca, 0xde, 0x04, 0x0d, 0x61, 0xce, 0x23, 0xa9, 0x9b, 0x04, 0xa2, 0x2f,
	0x7d, 0x46, 0xc4, 0xab, 0x4b, 0x08, 0x41, 0x87, 0x61, 0x3f, 0xd5, 0xbb, 0xc3, 0xf6, 0xfa, 0xec,
	0x48, 0x7c, 0xe6, 0xa4, 0xe7, 0x94, 0x91, 0x63, 0x97, 0x8e, 0x23, 0xa6, 0xf7, 0x86, 0xda, 0xfa,
	0xcc, 0x68, 0x96, 0xaf, 0xec, 0xf3, 0x05, 0xf4, 0x01, 0xdc, 0x70, 0x12, 0x7a, 0x4a, 0x22, 0x99,
	0xd0, 0x17, 0x09, 0x73, 0xd9, 0x9a, 0x48, 0xd9, 0xe9, 0xbe, 0x7b, 0xbb, 0xd2, 0xea, 0x6b, 0xe6,
	0x6b, 0x68, 0x1f, 0x62, 0x7f, 0xda, 0xfe, 0x11, 0x74, 0x22, 0x7c, 0x96, 0xb7, 0x2f, 0x3e, 0x23,
	0x0b, 0x7a, 0xa2, 0xfb, 0xc0, 0xd3, 0xdb, 0xc3, 0xf6, 0xd5, 0xf8, 0x2e, 0xcf, 0x3a, 0xf0, 0x0a,
	0xe5, 0x5f, 0x34, 0xe8, 0xed, 0xd3, 0xb3, 0x33, 0x12, 0xb1, 0x69, 0xe5, 0x75, 0xe8, 0xb9, 0x19,
	0x42, 0x56, 0x90, 0x3f, 0x2a, 0x2e, 0xb7, 0x55, 0x97, 0x2b, 0x35, 0x76, 0xfe, 0x4d, 0x44, 0xad,
	0xf1, 0x11, 0x2c, 0xec, 0x0b, 0x12, 0x3e, 0x24, 0x23, 0xf2, 0x6a, 0x4c, 0x52, 0x86, 0xee, 0x43,
	0x2f, 0xc6, 0x93, 0x90, 0xe2, 0xbc, 0xe2, 0x9b, 0x56, 0x7e, 0xda, 0x44, 0x5a, 0x1e, 0x35, 0x77,
	0x01, 0x55, 0xd1, 0x69, 0x4c, 0xa3, 0x94, 0xa0, 0xbb, 0xd0, 0x4d, 0x48, 0x3a, 0x0e, 0x59, 0x33,
	0x5a, 0x06, 0xcd, 0x3f, 0x34, 0x98, 0x7f, 0x16, 0xa4, 0xac, 0xaa, 0x6c, 0x43, 0xf7, 0x65, 0x10,
	0x32, 0x92, 0x48, 0xe8, 0xb2, 0x95, 0xcf, 0xbb, 0x85, 0xe3, 0xc0, 0xfa, 0x52, 0xc4, 0x82, 0xc8,
	0x1f, 0xc9, 0x34, 0xb4, 0x09, 0x7d, 0x9a, 0x78, 0x24, 0xe1, 0xa6, 0xb4, 0x64, 0xe3, 0x35, 0xc8,
	0x73, 0x9a, 0x30, 0x0e, 0xe8, 0x89, 0xb4, 0xbd, 0x09, 0xfa, 0x8c, 0x4b, 0x90, 0xd0, 0x4b, 0x85,
	0x89, 0x73, 0x5b, 0x6b, 0xaa, 0x04, 0x09, 0xbd, 0xe7, 0x44, 0x1e, 0xe3, 0x91, 0xcc, 0x45, 0x9b,
	0xd0, 0x8d, 0xb1, 0x1f, 0x44, 0xbe, 0xb4, 0x57, 0xaf, 0xa3, 0xbe, 0xe6, 0x31, 0x9c, 0x21, 0xb2,
	0x3c, 0x73, 0x17, 0x06, 0x65, 0x77, 0xd2, 0x99, 0xfb, 0xd0, 0xcb, 0x9a, 0x4f, 0x75, 0x4d, 0x4c,
	0x92, 0x6a, 0xac, 0x8c, 0x9a, 0x9f, 0xc3, 0xfc, 0x88, 0x60, 0xaf, 0x6a, 0xcd, 0x74, 0x13, 0x64,
	0x6e, 0xc3, 0xa0, 0x44, 0x5e, 0x6f, 0x43, 0x1e, 0xc1, 0xc2, 0x51, 0xec, 0xfd, 0x87, 0x59, 0xa8,
	0xa2, 0xaf, 0x27, 0xbd, 0x03, 0x03, 0x39, 0x48, 0xd8, 0xcf, 0x95, 0xef, 0xa9, 0xca, 0x37, 0x4a,
	0x2c, 0xf6, 0x4b, 0xe1, 0xed, 0x62, 0x84, 0x39, 0x56, 0xea, 0x7e, 0xa4, 0xe8, 0xd6, 0xb1, 0xb9,
	0xec, 0xef, 0x1a, 0xdc, 0x12, 0x9b, 0x54, 0xaa, 0xfe, 0x8f, 0x26, 0x70, 0x5b, 0x9e, 0xaf, 0x8a,
	0x2d, 0xf7, 0xd4, 0x01, 0x54, 0x3c, 0xcd, 0xe7, 0xef, 0x21, 0xdc, 0x12, 0x53, 0x54, 0xfa, 0x32,
	0xe5, 0xf8, 0x3d, 0x94, 0x83, 0x7b, 0xed, 0xad, 0xd8, 0x83, 0xdb, 0xd9, 0x2e, 0xca, 0x1b, 0x33,
	0xd7, 0x7d, 0xa0, 0x4e, 0xc1, 0xa0, 0x80, 0xe7, 0x99, 0xc5, 0x24, 0x3c, 0x86, 0x25, 0x85, 0x43,
	0x96, 0xb0, 0xae, 0x94, 0x70, 0x99, 0x23, 0x2f, 0xe3, 0x09, 0x20, 0xee, 0x99, 0x52, 0x44, 0xe5,
	0x76, 0xd5, 0xa6, 0xb8, 0x5d, 0xcd, 0xc7, 0xb0, 0x58, 0x63, 0x91, 0x65, 0x3c, 0x50, 0xdd, 0x6f,
	0xe8, 0x25, 0xdf, 0x81, 0x5d, 0x40, 0xdc, 0x48, 0xa5, 0x90, 0x29, 0x77, 0xe1, 0x0b, 0x58, 0xac,
	0x81, 0xaf, 0x6b, 0xc3, 0xd6, 0x5f, 0x2d, 0x98, 0xe1, 0x07, 0x34, 0x45, 0xdf, 0x42, 0x37, 0xf3,
	0x14, 0x19, 0x65, 0xb6, 0xfa, 0xc6, 0x30, 0x56, 0x1b, 0x63, 0x99, 0xac, 0xf9, 0xde, 0x8f, 0xbf,
	0xfd, 0xf9, 0x73, 0x6b, 0x60, 0xce, 0xd8, 0xdc, 0x9e, 0x9d, 0x7c, 0xbb, 0x50, 0x08, 0xdd, 0xec,
	0xc6, 0xa8, 0x50, 0x5f, 0xba, 0x80, 0x2a, 0xd4, 0x97, 0xaf, 0x17, 0xf3, 0x63, 0x41, 0xfd, 0xe1,
	0x96, 0x2e, 0xa8, 0xed, 0x37, 0x92, 0xda, 0x0a, 0x3c, 0xeb, 0x9c, 0xbb, 0xf1, 0x43, 0xa9, 0x76,
	0x04, 0x1d, 0xee, 0x09, 0xd2, 0x0b, 0x3e, 0xe5, 0x86, 0x35, 0x56, 0x1a, 0x22, 0x52, 0x47, 0x17,
	0x3a, 0x08, 0x0d, 0xa4, 0x4e, 0xc1, 0x8f, 0x9e, 0x42, 0x87, 0x6f, 0x75, 0x85, 0x56, 0x79, 0xa7,
	0x55, 0x68, 0xd5, 0xf7, 0x81, 0x79, 0x53, 0xd0, 0xf6, 0x50, 0xe6, 0x8c, 0xd1, 0x7f, 0xf7, 0x76,
	0xa5, 0xd3, 0xd7, 0x06, 0xda, 0xd6, 0x4f, 0x2d, 0xe8, 0x1c, 0xf2, 0xef, 0x41, 0x2f, 0x0a, 0xfb,
	0x57, 0x54, 0x8b, 0x8b, 0xb3, 0x69, 0x18, 0x4d, 0x21, 0x29, 0xb1, 0x24, 0x24, 0xe6, 0xcd, 0x8e,
	0xcd, 0xb0, 0x5f, 0xba, 0xf1, 0x95, 0x2c, 0x7b, 0xb9, 0x5e, 0x5c, 0xc9, 0xa9, 0x5f, 0x0e, 0x48,
	0xc6, 0x1b, 0x82, 0xb1, 0x8b, 0x04, 0x23, 0x1a, 0x49, 0x5b, 0x97, 0xeb, 0xe6, 0x35, 0x11, 0x29,
	0x17, 0x83, 0xb9, 0x2c, 0x88, 0x16, 0xd0, 0x3c, 0x27, 0xaa, 0x78, 0x5a, 0xf1, 0xe1, 0xd7, 0x16,
	0xf4, 0xe5, 0x6c, 0xa6, 0xc8, 0x29, 0xbc, 0xb8, 0xa3, 0x34, 0x5c, 0x3f, 0x25, 0xc6, 0xfb, 0x57,
	0x85, 0xa5, 0xf0, 0x8a, 0x10, 0x5e, 0x34, 0xfb, 0xb6, 0xfc, 0x76, 0x55, 0xfa, 0xe2, 0x4a, 0x5f,
	0x56, 0x6b, 0xed, 0x2b, 0xfc, 0x6b, 0xcd, 0x41, 0xc9, 0x3e, 0x14, 0xec, 0x06, 0xd2, 0x73, 0x76,
	0xfb, 0x8d, 0xbc, 0x3c, 0xf2, 0x99, 0xf9, 0x5e, 0x7a, 0xb6, 0x5a, 0xb3, 0xe6, 0x4a, 0x91, 0x86,
	0xa3, 0x6c, 0xae, 0x0a, 0x91, 0x25, 0xb4, 0x58, 0x8a, 0x34, 0xf8, 0xb7, 0xb7, 0xf9, 0x9d, 0x75,
	0x8d, 0xdf, 0x54, 0xbb, 0xb1, 0xe3, 0x74, 0xc5, 0xef, 0x86, 0x4f, 0xff, 0x09, 0x00, 0x00, 0xff,
	0xff, 0xa3, 0x29, 0x78, 0xb1, 0x8c, 0x0d, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ToolsClient is the client API for Tools service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ToolsClient interface {
	Create(ctx context.Context, in *CreateToolRequest, opts ...grpc.CallOption) (*CreateToolResponse, error)
	Update(ctx context.Context, in *UpdateToolRequest, opts ...grpc.CallOption) (*UpdateToolResponse, error)
	Read(ctx context.Context, in *ReadToolRequest, opts ...grpc.CallOption) (*ReadToolResponse, error)
	List(ctx context.Context, in *ListToolRequest, opts ...grpc.CallOption) (*ListToolResponse, error)
}

type toolsClient struct {
	cc *grpc.ClientConn
}

func NewToolsClient(cc *grpc.ClientConn) ToolsClient {
	return &toolsClient{cc}
}

func (c *toolsClient) Create(ctx context.Context, in *CreateToolRequest, opts ...grpc.CallOption) (*CreateToolResponse, error) {
	out := new(CreateToolResponse)
	err := c.cc.Invoke(ctx, "/service.Tools/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolsClient) Update(ctx context.Context, in *UpdateToolRequest, opts ...grpc.CallOption) (*UpdateToolResponse, error) {
	out := new(UpdateToolResponse)
	err := c.cc.Invoke(ctx, "/service.Tools/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolsClient) Read(ctx context.Context, in *ReadToolRequest, opts ...grpc.CallOption) (*ReadToolResponse, error) {
	out := new(ReadToolResponse)
	err := c.cc.Invoke(ctx, "/service.Tools/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolsClient) List(ctx context.Context, in *ListToolRequest, opts ...grpc.CallOption) (*ListToolResponse, error) {
	out := new(ListToolResponse)
	err := c.cc.Invoke(ctx, "/service.Tools/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ToolsServer is the server API for Tools service.
type ToolsServer interface {
	Create(context.Context, *CreateToolRequest) (*CreateToolResponse, error)
	Update(context.Context, *UpdateToolRequest) (*UpdateToolResponse, error)
	Read(context.Context, *ReadToolRequest) (*ReadToolResponse, error)
	List(context.Context, *ListToolRequest) (*ListToolResponse, error)
}

func RegisterToolsServer(s *grpc.Server, srv ToolsServer) {
	s.RegisterService(&_Tools_serviceDesc, srv)
}

func _Tools_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateToolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolsServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Tools/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolsServer).Create(ctx, req.(*CreateToolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tools_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateToolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolsServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Tools/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolsServer).Update(ctx, req.(*UpdateToolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tools_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadToolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolsServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Tools/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolsServer).Read(ctx, req.(*ReadToolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tools_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListToolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolsServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Tools/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolsServer).List(ctx, req.(*ListToolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Tools_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.Tools",
	HandlerType: (*ToolsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Tools_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Tools_Update_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _Tools_Read_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Tools_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/brocwoodworthIBLX/hack-db/pkg/pb/service.proto",
}

// TagsClient is the client API for Tags service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TagsClient interface {
	Create(ctx context.Context, in *CreateTagRequest, opts ...grpc.CallOption) (*CreateTagResponse, error)
	List(ctx context.Context, in *ListTagRequest, opts ...grpc.CallOption) (*ListTagResponse, error)
	Read(ctx context.Context, in *ReadTagRequest, opts ...grpc.CallOption) (*ReadTagResponse, error)
}

type tagsClient struct {
	cc *grpc.ClientConn
}

func NewTagsClient(cc *grpc.ClientConn) TagsClient {
	return &tagsClient{cc}
}

func (c *tagsClient) Create(ctx context.Context, in *CreateTagRequest, opts ...grpc.CallOption) (*CreateTagResponse, error) {
	out := new(CreateTagResponse)
	err := c.cc.Invoke(ctx, "/service.Tags/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tagsClient) List(ctx context.Context, in *ListTagRequest, opts ...grpc.CallOption) (*ListTagResponse, error) {
	out := new(ListTagResponse)
	err := c.cc.Invoke(ctx, "/service.Tags/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tagsClient) Read(ctx context.Context, in *ReadTagRequest, opts ...grpc.CallOption) (*ReadTagResponse, error) {
	out := new(ReadTagResponse)
	err := c.cc.Invoke(ctx, "/service.Tags/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TagsServer is the server API for Tags service.
type TagsServer interface {
	Create(context.Context, *CreateTagRequest) (*CreateTagResponse, error)
	List(context.Context, *ListTagRequest) (*ListTagResponse, error)
	Read(context.Context, *ReadTagRequest) (*ReadTagResponse, error)
}

func RegisterTagsServer(s *grpc.Server, srv TagsServer) {
	s.RegisterService(&_Tags_serviceDesc, srv)
}

func _Tags_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TagsServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Tags/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TagsServer).Create(ctx, req.(*CreateTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tags_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TagsServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Tags/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TagsServer).List(ctx, req.(*ListTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tags_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TagsServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Tags/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TagsServer).Read(ctx, req.(*ReadTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Tags_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.Tags",
	HandlerType: (*TagsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Tags_Create_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Tags_List_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _Tags_Read_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/brocwoodworthIBLX/hack-db/pkg/pb/service.proto",
}

// CommentsClient is the client API for Comments service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CommentsClient interface {
	Create(ctx context.Context, in *CreateCommentRequest, opts ...grpc.CallOption) (*CreateCommentResponse, error)
	List(ctx context.Context, in *ListCommentRequest, opts ...grpc.CallOption) (*ListCommentResponse, error)
	Read(ctx context.Context, in *ReadCommentRequest, opts ...grpc.CallOption) (*ReadCommentResponse, error)
}

type commentsClient struct {
	cc *grpc.ClientConn
}

func NewCommentsClient(cc *grpc.ClientConn) CommentsClient {
	return &commentsClient{cc}
}

func (c *commentsClient) Create(ctx context.Context, in *CreateCommentRequest, opts ...grpc.CallOption) (*CreateCommentResponse, error) {
	out := new(CreateCommentResponse)
	err := c.cc.Invoke(ctx, "/service.Comments/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentsClient) List(ctx context.Context, in *ListCommentRequest, opts ...grpc.CallOption) (*ListCommentResponse, error) {
	out := new(ListCommentResponse)
	err := c.cc.Invoke(ctx, "/service.Comments/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentsClient) Read(ctx context.Context, in *ReadCommentRequest, opts ...grpc.CallOption) (*ReadCommentResponse, error) {
	out := new(ReadCommentResponse)
	err := c.cc.Invoke(ctx, "/service.Comments/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommentsServer is the server API for Comments service.
type CommentsServer interface {
	Create(context.Context, *CreateCommentRequest) (*CreateCommentResponse, error)
	List(context.Context, *ListCommentRequest) (*ListCommentResponse, error)
	Read(context.Context, *ReadCommentRequest) (*ReadCommentResponse, error)
}

func RegisterCommentsServer(s *grpc.Server, srv CommentsServer) {
	s.RegisterService(&_Comments_serviceDesc, srv)
}

func _Comments_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentsServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Comments/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentsServer).Create(ctx, req.(*CreateCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comments_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentsServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Comments/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentsServer).List(ctx, req.(*ListCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comments_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentsServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Comments/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentsServer).Read(ctx, req.(*ReadCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Comments_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.Comments",
	HandlerType: (*CommentsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Comments_Create_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Comments_List_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _Comments_Read_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/brocwoodworthIBLX/hack-db/pkg/pb/service.proto",
}
